homepage/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('gallery/', views.gallery, name = 'gallery'),
    path('jadwal/', views.jadwal, name = 'jadwal'),
    path('createjadwal/', views.createJadwal, name = 'createJadwal'),
    path('jadwal/delete', views.delete, name = "delete"),

    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Jadwal(models.Model):
	nama_kegiatan = models.CharField(max_length = 50)
	kategori = models.CharField(max_length = 50)
	tempat = models.CharField(max_length = 50)
	tanggal = models.DateField(default = timezone.now)
	waktu = models.TimeField(default = timezone.now)

	def __str__(self):
		return self.nama_kegiatan

homepage/forms.py
from . import models
from django import forms

class FormJadwal(forms.ModelForm):
    nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder": "ex : Deadline PR 2 Matdas",
        }))

    kategori = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder":"ex : Tugas",

        }))

    tempat = forms.CharField(widget = forms.TextInput(attrs={
        "class" : "jadwalfields full",
        "required" : True,
        "placeholder":"ex : Lab Babe",
        }))

    tanggal = forms.DateField(widget = forms.SelectDateWidget(attrs={
        "class" : "datefield jadwalfields",
        "required" : True,
        }))

    waktu = forms.TimeField(widget = forms.TextInput(attrs={
        "class" : "datefield jadwalfields",
        "required" : True,
        "placeholder":"ex : 00:00",
        }))

    class Meta:
    	model = models.Jadwal
    	fields = ["nama_kegiatan", "kategori", "tempat", "tanggal", "waktu"]

homepage/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from .forms import FormJadwal
from .models import Jadwal
from django.utils import timezone
import datetime


# Create your views here.
def index(request):
    return render(request, 'index.html')

def gallery(request):
    return render(request, 'gallery.html')

def createJadwal(request):
	form =	FormJadwal()
	if request.method == "POST":
		form = FormJadwal(request.POST)
		if form.is_valid():
			form.save()
		return redirect('homepage:jadwal')
	return render(request, 'createJadwal.html', {'form' : form})

def jadwal(request):
	schedule = Jadwal.objects.order_by("tanggal", "waktu")
	response = {
		'jadwal' : schedule,
		'server_time' : timezone.now(),
	}
	return render(request, "jadwal.html", response)

def delete(request):
	if request.method == "POST":
		id = request.POST['id']
		Jadwal.objects.get(id=id).delete()
	return redirect('homepage:jadwal')

homepage/templates/createJadwal.html
<!DOCTYPE html>

{% load static %}

<html lang ='en'>
<head>
	<meta charset = "UTF-8">
	<meta name = "viewport" content = "width=device-width", initial-scale = 1.0">
	<meta http-equiv = "X-UA-Compatible" content = "ie=edge">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
	<link href='http://fonts.googleapis.com/css?family=Montserrat:light' rel='stylesheet' type='text/css'>
	<title> Create Schedule </title>
</head>

<nav class = "navbar navbar-expand-md navbar-dark bg-dark sticky-top">
<div class = "container-fluid">
	<a class="navbar-brand" href = "{% url 'homepage:index' %}"> Home </a>
	<button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target="#navbarResponsive">
		<span class = "navbar-toggler-icon"></span>
	</button>
	<div class = "collapse navbar-collapse" id = "navbarResponsive">
		<ul class = "navbar-nav ml-auto">
			<li class ="nav-item active">
				<a class = "nav-link" href = "{% url 'homepage:gallery' %}"> Gallery </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "{% url 'homepage:jadwal' %}"> Schedule </a>
			</li>
		</ul>
	</div>
</div>
</nav>


<h1> Create Schedule <h1>
<div class = "col-6" id ="field">
	<form method = "POST" class = "form">
		{% csrf_token %}
		<p> Nama Kegiatan </p>
		{{form.nama_kegiatan}}
		<p> Kategori </p>
		{{form.kategori}} </br>
		<p> Tempat </p> 
		{{form.tempat}} </br>
		<p> Tanggal </p>
		{{form.tanggal}}
		<p> Waktu </p>
		{{form.waktu}}
		<p> </p>
	    <div class="full">
            <input type="submit" class="button" value="Submit" />
        </div>
</form>

</html>

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
		<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
		<link rel = "stylesheet" type = "text/css" href = "{% static 'css/style1.css' %}" />
		<link href='http://fonts.googleapis.com/css?family=Montserrat:light' rel='stylesheet' type='text/css'>
		<title> Gallery </title>
</head>

<nav class = "navbar navbar-expand-md navbar-dark bg-dark sticky-top">
<div class = "container-fluid">
	<a class="navbar-brand mx-auto" href = "{% url 'homepage:index' %}"> Home </a>
	<button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target="#navbarResponsive">
		<span class = "navbar-toggler-icon"></span>
	</button>
	<div class = "collapse navbar-collapse" id = "navbarResponsive">
		<ul class = "navbar-nav ml-auto">
			<li class ="nav-item active">
				<a class = "nav-link" href = "{% url 'homepage:jadwal' %}"> Schedule </a>
			</li>
		</ul>
	</div>
</div>
</nav>

<body>
	<div class = "container">
		<h3 style = "margin-top : 75px"> gallery </h3>
		<div class = "row">
			<div class = "col-sm-6">
				<div class = "pict">
					<img src = "{% static 'images/1.jpg' %}" style = "height : 400px; width : 400px; margin : 20px">
					<img src = "{% static 'images/2.jpg' %}" style = "height : 400px; width : 400px; margin : 20px">
				</div>
			</div>
			<div class = "col-sm-6">
				<div class = "pict">
					<img src = "{% static 'images/3.jpg' %}" style = "height : 400px; width : 400px; margin : 20px">
					<img src = "{% static 'images/4.jpg' %}" style = "height : 400px; width : 400px; margin : 20px">
				</div>
			</div>
		</div>
	</div>
</body>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang= "en">

<head>
	<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}"/>	
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/style1.css' %}" />
	<link href= 'http://fonts.googleapis.com/css?family=Montserrat:light' rel='stylesheet' type='text/css'>
	<script src = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"> </script>
	<title> Home </title>
</head>

{% include "navbar.html" %}

<body id = "Home">
	<div class = "frame1">
		<div class = "box">
			<div class = "container">
				<h1> Hi, I'm Daniel </h1>
				<hr style = "width : 75%">
				<hr>
			</div>
		</div>
	</div>
	<div id = "About" class = "frame2" style = "height : 750px">
		<div class = "box">
			<img src = "{% static 'images/foto2.jpg' %}" style= "float:left; position : relative; border-radius :50%; width :300px; height :300px; top : 10%; margin : 50px">
			<div>
				<h2> about me</h2>
				<hr style = "position :absolute; left : 30%">
				<p style = "margin : 50px"> Hi! I am Daniel Martin. I am currently on my second year studying Computer Science at Universitas Indonesia. <b>Singing</b> and <b>doing computer stuff</b> is my passion.</p>
			</div>
		</div>
	</div>

	<div id = "Experiences" class = "frame1" style = "height : 800px">
		<div class = "content-align-left">
			<h2> experiences </h2>
			<hr style = "position : absolute; width : 30%">
			<h3 style = "padding-top : 50px"> education </h3>
			<p> 2006 - 2012 SD Regina Pacis Jakarta</p>
			<p> 2012 - 2015 SMP Regina Pacis Jakarta</p>
			<p> 2015 - 2018 SMAN 65 Jakarta </p>
			<p> 2018 - present Universitas Indonesia </p>

			<h3> organization </h3>
			<p> 2018 - present PSM Paragita </p>
		</div>
	</div>


	<div id = "Skills" class = "frame2" style = "height : 1100px">
		<div class = "container">
			<h2> skills</h2>
			<hr style = "width : 30%">
			<div class = "box_skills">
				<h3> technical skills </h3>
				<div class = "row">
					<div class = "col-sm-4">
						<div class = "pict">
							<img src = "{% static 'images/python.png' %}">
						</div>
						<div class = "paragraph_skills">
							<p> Python </p>
							<p> 9/10 </p>
						</div>
					</div>
					<div class = "col-sm-4">
						<div class = "pict">
							<img src = "{% static 'images/javaa.png' %}">
						</div>
						<div class = "paragraph_skills">
							<p> Java </p>
							<p> 8/10 </p>
						</div>
					</div>
					<div class = "col-sm-4">
						<div class = "pict">
							<img src = "{% static 'images/microsoft.png' %}">
						</div>
						<div class = "paragraph_skills">
							<p> Microsoft Office </p>
							<p> 9/10 </p>
						</div>
					</div>
				</div>
			</div>

			<div class = "box_skills" style = "height :250px">
				<h3> languages </h3>
				<p> English 9/10 </p>
				<p> Indonesia 9/10 </p>
			</div>

		</div>
	</div>

	<div class = "container">
		<div id = "Contact" class = "frame1" style = "height : 720px">
			<h2> contact</h2>
			<hr>
			<div style= "width: 80%; margin: auto; margin-top : 50px; ">
				<a href = "https://www.instagram.com/danielmartinn/"> <img src = "{% static 'images/insta.png' %}" style = "margin : 10px"> </a>
				<a href = "https://www.linkedin.com/in/daniel-martin-661201180/"> <img src = "{% static 'images/lnkdin.png' %}" style = "margin : 10px"> </a>
			</div>

			<div style = "margin-top: 50px">
				<p> <img src = "{% static 'images/phone.png' %}"> 087876669593 </p>
				<p> <img src = "{% static 'images/mail.png' %}"> danielmartin.sibarani@gmail.com </p>
			</div>
		</div>
	</div>
</body>

homepage/templates/jadwal.html
<!DOCTYPE html>

{% load static %}
<html lang ='en'>
<head>
	<meta charset = "UTF-8">
	<meta name = "viewport" content = "width=device-width", initial-scale = 1.0">
	<meta http-equiv = "X-UA-Compatible" content = "ie=edge">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
	<link href='http://fonts.googleapis.com/css?family=Montserrat:light' rel='stylesheet' type='text/css'>
	<title> Schedule </title>
</head>

<nav class = "navbar navbar-expand-md navbar-dark bg-dark sticky-top">
<div class = "container-fluid">
	<a class="navbar-brand" href = "{% url 'homepage:index' %}"> Home </a>
	<button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target="#navbarResponsive">
		<span class = "navbar-toggler-icon"></span>
	</button>
	<div class = "collapse navbar-collapse" id = "navbarResponsive">
		<ul class = "navbar-nav ml-auto">
			<li class ="nav-item active">
				<a class = "nav-link" href = "{% url 'homepage:gallery' %}"> Gallery </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "{% url 'homepage:createJadwal' %}"> Create Schedule </a>
			</li>
		</ul>
	</div>
</div>
</nav>

<body>
	{% for j in jadwal %}
	<div class="jadwal-card">
        <h2>{{j.kategori}} - {{ j.nama_kegiatan }}</h2>
        <div class="flex">
        	<p> Tempat  : {{j.tempat}} </br>
        		Tanggal : {{j.tanggal}} </br>
        		Waktu   : {{j.waktu}} </p>
            <form action="delete" method="POST">
                {% csrf_token %}
                <input type= "hidden" value="{{ j.id }}" name="id" />
                <input class= "button delete" type="submit" value= "Delete" />
            </form>
        </div>
	</div>
	{% endfor %}
</body>
</html>

homepage/templates/navbar.html
<nav class = "navbar navbar-expand-md navbar-dark bg-dark sticky-top">
<div class = "container-fluid">
	<a class="navbar-brand" href = "#Home"> Home </a>
	<button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target="#navbarResponsive">
		<span class = "navbar-toggler-icon"></span>
	</button>
	<div class = "collapse navbar-collapse" id = "navbarResponsive">
		<ul class = "navbar-nav ml-auto">
			<li class ="nav-item active">
				<a class = "nav-link" href = "#About"> About </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "#Experiences"> Experiences </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "#Skills"> Skills </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "#Contact"> Contact </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "{% url 'homepage:gallery' %}"> Gallery </a>
			</li>
			<li class = "nav-item">
				<a class = "nav-link" href = "{% url 'homepage:jadwal' %}"> Schedule </a>
		</ul>
	</div>
</div>
</nav>